//alex created
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import IntroStep_1 from "./introStep_1";
import IntroStep_2 from "./introStep_2";
import IntroStep_3 from "./introStep_3";
import IntroStep_4 from "./introStep_4";
import IntroStep_5 from "./introStep_5";
import IntroStep_6 from "./introStep_6";

export default function Intro() {
  const [stepId, setStepId] = useState(1);
  const handleStepId = (id) => setStepId(id);
  // console.log("stepId", stepId);
  return (
    <div className="w-full h-full">
      {/* <Head>
        <title>Lamboozled Game</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/site_icon.png" />
      </Head> */}
      {stepId == 1 && <IntroStep_1 handleStepId={handleStepId} />}
      {stepId == 2 && <IntroStep_2 handleStepId={handleStepId} />}
      {stepId == 3 && <IntroStep_3 handleStepId={handleStepId} />}
      {stepId == 4 && <IntroStep_4 handleStepId={handleStepId} />}
      {stepId == 5 && <IntroStep_5 handleStepId={handleStepId} />}
      {stepId == 6 && <IntroStep_6 handleStepId={handleStepId} />}
    </div>
  );
}
