import Head from "next/head";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import BlogMain from "../components/Blog/BlogMain";

export default function Blog() {
  return (
    <div className="bg-[#F5F5F5]">
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header color />
      <BlogMain />
      <Footer />
    </div>
  );
}
