import Head from "next/head";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import EventMain from "../components/Event/EventMain";

export default function Event() {
  return (
    <div className="bg-[#F5F5F5]">
      <Head>
        <title>Event</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header color />
      <EventMain />
      <Footer />
    </div>
  );
}
