import Head from "next/head";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import FaqMain from "../components/Faqs/FaqMain";
import Faq from "../components/Courses/Faq";

export default function FAQs() {
  return (
    <div className="bg-[#F5F5F5]">
      <Head>
        <title>FQAs</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header color />
      <FaqMain />
      <Faq />
      <Footer />
    </div>
  );
}
