import Head from "next/head";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import HistoryMain from "../components/History/Historymain";
import LastestNews from "../components/History/LastestNews";
import Teams from "../components/History/Teams";

export default function History() {
  return (
    <div className="bg-[#F5F5F5]">
      <Head>
        <title>History</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header color />
      <HistoryMain />
      <LastestNews />
      <Teams />
      <Footer />
    </div>
  );
}
