import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import IntroStep_1 from '../components/intro/introStep_1'
import IntroStep_2 from '../components/intro/introStep_2'

export default function Home() {
  const [stepId, setStepId] = useState(1);
  const handleStepId = (id) => setStepId(id);
  return (
    <div className="bg-black w-screen h-screen">
      <Head>
        <title>Lamboozled Game</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/site_icon.png" />
      </Head>
      {stepId==1 && (
        <IntroStep_1 handleStepId = {handleStepId} />
      )}
      {stepId==2 && (
        <IntroStep_2 handleStepId = {handleStepId} />
      )}
    </div>
  )
}
