import Head from 'next/head'
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import LoginMain from "../components/Auth/LoginMain";

export default function Login() {
  return (
    <div className="">
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <LoginMain />
    </div>
  );
}
