import Head from "next/head";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import ProgramsMain from "../components/Programs/ProgramsMain";
import BercDemo from "../components/Programs/BercDemo";

export default function Programs() {
  return (
    <div className="bg-[#F5F5F5]">
      <Head>
        <title>Programs</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header color />
      <ProgramsMain />
      <BercDemo />
      <Footer />
    </div>
  );
}
