import RegisterMain from "../components/Auth/RegisterMain";
import Head from "next/head";

export default function register() {
  return (
    <div className="">
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <RegisterMain />
    </div>
  );
}
