import Head from "next/head";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import ResourcesMain from "../components/Resources/ResourcesMain";

export default function Resources() {
  return (
    <div className="bg-[#F5F5F5]">
      <Head>
        <title>Resources</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header color />
      <ResourcesMain />
      <Footer />
    </div>
  );
}
