// Alex created
import Head from 'next/head'
import Image from 'next/image'
import Basic_new from '../components/basics/Basic_new'
import Submitted from '../components/basics/Submitted'



export default function Home() {
  return (
    <div className=" w-screen h-screen">
      <Head>
        <title>Lamboozled Game</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/site_icon.png" />
      </Head>
      <Submitted />
    </div>
  )
}
