import Head from "next/head";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import BercDemo from "../components/Programs/BercDemo";
import TeamsMain from "../components/Teams/TeamsMain";

export default function Teams() {
  return (
    <div className="bg-[#F5F5F5]">
      <Head>
        <title>Teams</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header color />
      <TeamsMain />
      <BercDemo />
      <Footer />
    </div>
  );
}
