import Head from 'next/head'
import Toolbox from '../components/toolbox/Toolbox'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Lamboozled Game</title>
        <meta name="description" content="Generated by leopard" />
        <link rel="icon" href="/site_icon.png" />
      </Head>
     <Toolbox />

    </div>
  )
}
